require("user.options")
require("user.lazy")
require("user.keymaps")
require("user.highlight_yank")
require("user.rotate_windows")
require("user.resize_windows")
require("user.vertical_help")
require("user.toggle_diagnostics")
require("user.copy_file_path_to_clipboard")
require("user.set_file_type")

vim.cmd("colorscheme kanagawa-dragon")
vim.cmd("highlight! HarpoonInactive guibg=NONE guifg=#63698c")
vim.cmd("highlight! HarpoonActive guibg=NONE guifg=white")
vim.cmd("highlight! HarpoonNumberActive guibg=NONE guifg=#7aa2f7")
vim.cmd("highlight! HarpoonNumberInactive guibg=NONE guifg=#7aa2f7")
vim.cmd("highlight! TabLineFill guibg=NONE guifg=white")
